SELECT COUNTRY,
	COUNT(DISTINCT CUSTOMER_KEY) AS TOTAL_CUSTOMERS
FROM 
	dim_customers
GROUP BY COUNTRY
ORDER BY TOTAL_CUSTOMERS DESC;

SELECT GENDER,
	COUNT(DISTINCT CUSTOMER_KEY) AS TOTAL_CUSTOMERS
FROM 
	dim_customers
GROUP BY GENDER
ORDER BY TOTAL_CUSTOMERS DESC;

SELECT
	  CATEGORY,
     COUNT(DISTINCT PRODUCT_KEY) AS TOTAL_PRODUCTS
FROM dim_products
GROUP BY category
ORDER BY TOTAL_PRODUCTS DESC; 

SELECT
	CATEGORY,
    AVG(COST) AS AVG_COST
FROM dim_products
GROUP BY category
ORDER BY AVG_COST DESC;


SELECT
	P.CATEGORY,
	SUM(F.SALES_AMOUNT) AS TOTAL_REVENUE
FROM dim_products AS P
LEFT JOIN fact_sales AS F
ON F.product_key=P.product_key
GROUP BY CATEGORY
ORDER BY TOTAL_REVENUE DESC;


SELECT
	C.COUNTRY,
    SUM(F.QUANTITY) AS TOTAL_SOLD_ITEMS
FROM DIM_CUSTOMERS AS C
LEFT JOIN FACT_SALES AS F
ON C.CUSTOMER_KEY=F.CUSTOMER_KEY
GROUP BY C.COUNTRY
ORDER BY TOTAL_SOLD_ITEMS DESC;


SELECT
    p.subcategory,
    SUM(s.sales_amount) AS total_sales
FROM fact_sales s
JOIN dim_products p
    ON s.product_key = p.product_key
GROUP BY p.subcategory
ORDER BY total_sales DESC;


SELECT
    s.customer_key,
    SUM(s.sales_amount) AS total_sales
FROM fact_sales s
GROUP BY s.customer_key
ORDER BY total_sales DESC;

