SELECT 

	P.PRODUCT_NAME AS NAME,
	SUM(F.SALES_AMOUNT) AS TOTAL_REVENUE
FROM DIM_PRODUCTS AS P
LEFT JOIN FACT_SALES AS F
ON P.PRODUCT_KEY = F.PRODUCT_KEY
GROUP BY P.PRODUCT_NAME
ORDER BY TOTAL_REVENUE DESC
LIMIT 5;


SELECT 
    P.PRODUCT_NAME AS NAME, SUM(F.SALES_AMOUNT) AS TOTAL_REVENUE
FROM
    DIM_PRODUCTS AS P
        LEFT JOIN
    FACT_SALES AS F ON P.PRODUCT_KEY = F.PRODUCT_KEY
GROUP BY P.PRODUCT_NAME
ORDER BY TOTAL_REVENUE
LIMIT 5;

SELECT
	C.CUSTOMER_KEY,
    C.FIRST_NAME,
    C.LAST_NAME,
    SUM(F.SALES_AMOUNT) AS TOTAL_REVENUE
FROM
DIM_CUSTOMERS AS C
LEFT JOIN 
FACT_SALES AS F
ON C.CUSTOMER_KEY = F.CUSTOMER_KEY
GROUP BY 
	C.CUSTOMER_KEY,
    C.FIRST_NAME,
    C.LAST_NAME
ORDER BY TOTAL_REVENUE DESC
LIMIT 10;

SELECT * FROM FACT_SALES;
SELECT
	C.CUSTOMER_KEY,
    C.FIRST_NAME,
    C.LAST_NAME,
    COUNT(F.ORDER_NUMBER) AS TOTAL_ORDERS
FROM
DIM_CUSTOMERS AS C
LEFT JOIN 
FACT_SALES AS F
ON C.CUSTOMER_KEY = F.CUSTOMER_KEY
GROUP BY 
	C.CUSTOMER_KEY,
    C.FIRST_NAME,
    C.LAST_NAME
ORDER BY TOTAL_ORDERS 
LIMIT 3;



SELECT
    p.category,
    SUM(s.sales_amount) AS total_sales
FROM fact_sales s
JOIN dim_products p
    ON s.product_key = p.product_key
GROUP BY p.category
ORDER BY total_sales DESC;



SELECT
    p.product_name,
    SUM(s.sales_amount) AS total_sales,
    RANK() OVER (
        ORDER BY SUM(s.sales_amount) DESC
    ) AS sales_rank
FROM fact_sales s
JOIN dim_products p
    ON s.product_key = p.product_key
GROUP BY p.product_name;
